# Any parameters here affects the Earth daemon

# Configuration for doing user and group name lookup from uid and gid
#ldap_server_name: 'ldap.syd.rsp.com.au'
ldap_server_port: 389
ldap_user_lookup:
  base: "ou=people, dc=rsp, dc=com, dc=au"
  id_field: "uidNumber"
  name_field: "uid"
ldap_cache_time: 1.days
