development:
  adapter: postgresql
  database: rspintranet
  username: rspintra
  password: 
  host: localhost

test:
  adapter: postgresql
  database: rspintra_test
  username: postgres
  password:
  host: localhost

production:
  adapter: postgresql
  database: rspintranet
  username: rspintra
  password: 
  host: localhost
